import pathlib
L = []
L.append('# Risk Management Plan')
L.append('')
L.append('## 로컬 CBCT 웹 뷰어')
L.append('')
L.append('### 문서 정보')
L.append('')
L.append('| 항목 | 내용 |')
L.append('|------|------|')
L.append('| 프로젝트 | PLAYG |')
L.append('| Phase | PA |')
L.append('| 버전 | 1.0 |')
L.append('| Software Safety Class | Class A (IEC 62304) |')
L.append('| 문서 ID | PLAYG-1966 |')
L.append('| 작성일 | 2026-05-06 |')
L.append('| 상태 | Drafting |')
pathlib.Path("docs/PLAYG-1966/risk-management-plan.md").write_text("\n".join(L), encoding="utf-8")
print("Done part 1")
